---
- hosts: docker
  become: true
  vars:
    containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - 15672:15672
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
  roles:
    - common
    - docker
